Jarmode execution full pipeline. (one configured for cf-6282, others will be added one by one)
tahiat/specimin-evaluation pull request #37
Opened 2024-04-10 16:33 UTC by tahiat

2024-04-10 17:02 UTC, tahiat commented
existing compilation check script could have been modified support jar mode, but instead copied and made separate script

2024-04-10 17:39 UTC, kelloggm requested changes

2024-04-10 17:39 UTC, kelloggm commented on check_jar_mode_compilation.sh
> +#!/bin/sh
Are there any differences between this script and the approximate mode checking script other than the name of the output .json file? If not, I think it's much better to only have one script and make that a parameter.

2024-04-11 18:53 UTC, tahiat commented
Professor, I added dependency pulling scripts (not in this pR) for few projects in respective forked repos. 
Projects where I have not added the jar pull scripts:
daikon-1291 | calcite - 3619, 3850 | beam- 6388

2024-04-11 18:53 UTC, kelloggm approved these changes
I don't need to review again after the one thing is fixed.

2024-04-11 18:53 UTC, kelloggm commented on main.py
> +specimin_jar_output = 'jar_output'
Duplicate line

2024-04-11 18:57 UTC, merged